unbind C-b

set -g prefix M-q

bind M-q send-prefix

bind i split-window -h

bind - split-window -v

unbind x
bind k kill-pane

set -g mouse on

set -s set-clipboard external
set -as terminal-overrides ',xterm*:Ms=\E]52;%p1%s;%p2%s\007'

set -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel
bind-key -T copy-mode-vi Escape send-keys -X clear-selection

